-- Add missing columns to services table
-- Run this in Supabase SQL Editor

ALTER TABLE services ADD COLUMN IF NOT EXISTS endpoint TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS method TEXT DEFAULT 'POST';
ALTER TABLE services ADD COLUMN IF NOT EXISTS rateLimit INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS timeout INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS retryPolicy TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS responseFormat TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS schema TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS usageExamples TEXT[];
